"""create tables

Revision ID: 80015147d630
Revises: 07cb94a3f501
Create Date: 2023-05-31 11:02:30.503882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80015147d630'
down_revision = '07cb94a3f501'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signups', schema=None) as batch_op:
        batch_op.drop_column('time')

    # ### end Alembic commands ###
